### ISSUE TITLE
groups/edit: various channel editing mishaps

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1035]
During testing, @zalberico ran into several issues with the front-end of the channel editor getting out of sync with ship state. Our dream of direct manipulation is nice, but only works if the execution is flawless.

To combat this without a wholesale rewrite of editing the zone/channel model, I propose (with @urcades' OK) we add a "Save" button to the channel-editing form thusly:

![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/52aa1675-84e1-4f1a-b149-57ec35728274)

- This Save button should appear after any changes to the group channel structure such as rearranging zones, adding/removing/renaming channels, etc.
- The front-end should update optimistically and immediately.
- The save button should effectively submit these changes to the back-end, and disappear when the action is complete.
- Navigating away from this page in an unsaved state should present a window.confirm warning ("You have made unsaved changes to your group. Navigate away?" or something of the sort).

**Comment by rcrdlbl** [comment]
I have some concerns:

- A) The "Done" window renaming/privacy modal already serves as a "save" button – it sends a request to the API, if this isn't working, sending the request from a different button won't change anything
- B) Has zach had reliability issues with deleting a channel? It's also a single endpoint request – I think this would be better served with an error state and not "Save Deleting This Channel" which is imo kind of a bonkers interaction, like i expect everyone to complain about this
- C) The way "Move Channel" requests are currently made is "Move This Channel to This Position in This Zone" – without an API endpoint that lets us send the entire new channel ordering structure over, we'd have to loop through each channel move operation, which would make the "moving channels too fast and having order dropped" bugs MORE common, and not less – basically to implement a save button like that we'd need backend changes

**Comment by urcades** [comment]
@jamesacklin dan and I were talking about this a little today, and I'm more or less aligned on the primary point that **Adding**, **Removing**, and **Renaming** channels all occur in modal dialogs, and thus should already have some explicit "save" functions we shouldn't need to duplicate.

On the point of saving the state of a channel/section re-ordering, I'd just want to defer to whatever is the most performant or straightforward to implement. 

I've already mentioned to you out of band that the ideal here would just to have rearranging actions "just work" and optimistically retain state locally before propagating changes to other people, but since That's a Lot of Work, a single button for saving channel reordering is acceptable.
