### ISSUE TITLE
talk: clicking "talk" brings user to <DMHome/>, which is an empty component.

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1041]
**Describe the bug**
I'm fairly certain this should bring the user to Notifications. @urcades @jamesacklin

**Comment by jamesacklin** [comment]
This is by design - we should have a truly empty state and no notifications stream in Talk itself: https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1292%3A69053

**Comment by urcades** [comment]
Yeah the idea here is to generally approximate the pattern of most other standalone messaging apps which don’t feature a notifications stream within them, given purist messaging apps are essentially notification machines by their nature — this doesn’t excuse the lack of a good default “root” of the app.In earlier expansions of the design intent behind this app the idea was to always revert the state of the app to the last visited DM or talk channel such that one rarely, if ever, sees an “empty root” state in the talk app.Given this might not be possible, we should potentially consider placing a DM-creating button, or some onboarding prompt in the blank space.On Oct 28, 2022, at 13:28, james acklin ***@***.***> wrote:﻿
This is by design - we should have a truly empty state and no notifications stream in Talk itself: https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1292%3A69053

**Comment by patosullivan** [comment]
Closed since this is expected behavior.
