### ISSUE TITLE
groups: on join, if there are no default channels, bring user to All Channels

### ISSUE THREAD

**Issue by jyng** [tloncorp/landscape-apps#1164]
Upon joining a group, if there are no default channels set, bring the user to All Channels so that they may select some channels to join.

Screen capture below shows the existing behavior (user needs to know to click "All Channels", otherwise sees a completely empty group).

https://images.zenhubusercontent.com/477888647/35c2e604-333a-411a-92a9-94667279d115/screen_recording_2022_11_22_at_10_02_36_am.mov

**Comment by rcrdlbl** [comment]
<img width="1230" alt="Screen Shot 2022-11-20 at 2 46 06 AM" src="https://user-images.githubusercontent.com/40729534/202891466-ef76f6a4-c07e-4b00-9151-747cf8e76d15.png">
We currently already have this feature.
@patosullivan mentioned this may be because Finned Grouper was lost when he nuked his planet, but it remained in your channel sidebar.

**Comment by jamesacklin** [comment]
![Untitled.jpg](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/61159782-7e05-469c-b62b-358be47a3f92)

**Comment by jamesacklin** [comment]
Cleaning this issue up a bit. The original issue was about two different things.
