### ISSUE TITLE
groups/mobile: missing functions

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1266]
We are missing several functions on mobile:
- [ ] All channels in a group
- [ ] Leave group
- [x] Copy group link (context menu in groups list)
- [x] Pin group (context menu in groups list)

Will need placement advice from @urcades.

**Comment by urcades** [comment]
Some simple interventions for the remaining functions, using mostly existing interface patterns:

![Screenshot 2022-11-30 at 4 38 42 PM](https://user-images.githubusercontent.com/1195363/204913903-2a4018b7-c296-4fb1-89e6-fa738420ff35.png)

"All Channels" takes the form of a new row at the top of the channels list in the "Channels" tab. When tapped, we should transition the screen to another vertical scroll reminiscent of our current "All Channels" interface. Channels can then be joined or left from this interface.

Thinking about situating the "Leave Group" function, I decided to replace the current "Invite" tab, which doesn't really have an analogue on desktop, with an "Options" menu reminiscent of the menu we surface for the Groups app itself:

![Screenshot 2022-11-30 at 4 38 38 PM](https://user-images.githubusercontent.com/1195363/204914310-697f996d-d5a5-4b65-bfed-175c3fde9487.png)

Rather than take the user to a new page, I wanted to adopt a pattern (a drawer) more aligned with the dropdown that we use on desktop. It's a little funny to have a shelf menu emanate from a tab bar selection, but I think this is an OK interstitial state until we actually spend serious time thinking about how to implement our mobile apps.

I think these are fine interfaces to answer what we most immediately need to implement. 

I'll be attaching some designs that push the envelope a little bit towards where we actually should take these mobile interfaces in a following reply to this issue.
