### ISSUE TITLE
profiles: @p appears twice with no-nicknames set

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1385]

**Comment by jamesacklin** [comment]
![image.png](https://images.zenhubusercontent.com/6245cc0024d90711bcf4ea06/a044d259-b1c2-4338-b165-0dd69da81820)

**Comment by urcades** [comment]
This appears fixed in the system as I've observed it. 

Worth noting that at some point in our product's history, some people didn't like the monospace font used to render @ps and ended up rewriting their urbit's name using the "user set name" field, which now (due to our uniform typography) appears "duplicated".
