### ISSUE TITLE
groups: admins cannot delete chat messages they did not write

### ISSUE THREAD

**Issue by litmus-ritten** [tloncorp/landscape-apps#1428]
Previously, administrators were able to delete group chat messages written by other users. This is an important moderation function. This functionality is missing in the Landscape 1 groups interface.

**To Reproduce**
1. As the administrator of a group, mouse-over a message written by someone else.
2. Note the absence of a red X in the popup palette, forbidding deletion of the message.

**Expected behaviour**
Administrators should have the ability to remove any chat message, perhaps with the exception of messages written by other administrators or the group owner.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted with CLI
- OS/browser: Vivaldi on Linux

**Comment by willbach** [comment]
I'm seeing an odd bug where I am able to delete messages even in groups of which I was never an admin. In the Members list I am listed as an admin. I know of other users with the same bug, except that I do not appear as an admin to them. So each user appears to himself to be an admin and is able to delete posts.

Maybe it's because permissions were changed during migration?

**Comment by litmus-ritten** [comment]
@willbach That sounds like the thematic opposite of what I describe, and—if I understand you correctly—a potentially very serious privilege escalation bug.
