### ISSUE TITLE
Only have one group image

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1481]
**Describe the bug, optionally with screenshots**
Currently we have both group image and group icon. This feels wrong. The group image should be downscaled and used as the group icon. I don't think we need these to be distinct or to overlap.

**Comment by litmus-ritten** [comment]
I strongly disagree: the hero image for the group is rendered much larger than the iconic form. The relative sizes of these two contexts places different demands on graphical design which are not easily reconciled in a single graphic, and therefore it makes sense to have two separate images.

To give an example (and this does betray a conflict of interest, because I did put a decent amount of effort into these graphics), see the following:

![urbit - contextual alternates](https://user-images.githubusercontent.com/62781197/207526547-14c61d55-446e-437d-940a-29f3e8d17bd9.png)

Here, the big logo looks pretty nice IMO, but would not look very good or legible if shrunk down to the size of the iconic representation. Contrariwise, the iconic representation would look pretty boring enlarged to the size of the big logo, and would also break graphical continuity with the pre-Landscape 1 era. The large logos for the other groups indicated here are variations on the same basic concept.

To give a non-Urbit example, the aforementioned consideration informs how raster icons were implemented in Windows (and no doubt other operating systems as well). Icon files can store different graphical representations of the same object or concept, optimised for different resolutions/display sizes. As an example, an icon representing _'My Computer'_ may appear in a highly detailed isometric form optimised for maximum size on a high-DPI device. But, as it is scaled down it turns into an abstract, rectilinear representation of a computer monitor which still retains legibility in the context of a tree view in Explorer.

**Comment by zalberico** [comment]
I don't think this considers what it's like for users (especially on mobile) and isn't a great default experience.

My Computer is an OS icon, designed and shipped as part of the system. Here we're asking users to both add an image for their group and then craft a second appropriate icon for use in things like the group list. It'd be like slack having users make icons for UI elements.

I think this is confusing and the default behavior (especially with the current problems with the image setting UX) is that users will set a group image but still not see that image in the groups list.

Then they have to set a second image in the groups list (which if different now doesn't obviously connect that image to the group).

This is particularly noticeable on mobile (our most important UI) where the group relies on the image to differentiate itself in the list.

I'd argue we should at least set it by default to the group image if the icon has not been set.

![image](https://user-images.githubusercontent.com/441466/207598111-15878cca-e63a-495c-aac7-d0f6f2628667.jpeg)

**Comment by jamesacklin** [comment]
@zalberico The group cover is a deliberate product decision designed to echo personal profiles. I agree that the group customizing UX could be better since at the moment it's purely functional. Let's save this for a refurb later in 2023.
