### ISSUE TITLE
talk: update MessageHero, multi-DM meta to use sigils

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1516]
Right now the multi-party dm defaults to having the first letter of whatever the group is named. You can also set an image, but that requires s3. I think defaulting to something that uses the sigils of the members, or making it easy to set a few built in images (emojis?) for the group would be good. iOS does something like this.

**Comment by urcades** [comment]
This isn't a perfect solve for visibility's sake, but we can consider "stacking" 16px avatars in a diagonal pattern in the sidebar row, such that they fit in the existing boundary of the 24px sidebar icon/avatar area:

<img width="981" alt="Screenshot 2023-03-30 at 10 15 52 AM" src="https://user-images.githubusercontent.com/1195363/228868185-e8c1cf8c-5617-4ebc-8050-a0ca9dd94b62.png">

The latter of these examples shows a possible participant count we can consider implementing for Group DMs larger than 3 people.

**Comment by urcades** [comment]
To Zack's latter point, we've also played with the idea of setting Group DM avatars/representations to the "Text" Icon Box type, so that we get an appearance along these lines:

<img width="814" alt="Screenshot 2023-03-30 at 10 29 13 AM" src="https://user-images.githubusercontent.com/1195363/228869154-d3e9a433-800f-49c7-9d52-c549973689d7.png">

In this case, because the group is named "Heaven's Gang", the group shows up as an `H`. The background color of the avatar could be set randomly from a limited set of Indigo colors, or default to Black. Emoji are implicitly supported here:

<img width="772" alt="Screenshot 2023-03-30 at 10 30 50 AM" src="https://user-images.githubusercontent.com/1195363/228869625-bd217da0-46f1-4331-aaef-bdae9e7dcd06.png">
