### ISSUE TITLE
notebooks: migrated notebooks invisible to other users until permissions are set/changed

### ISSUE THREAD

**Issue by litmus-ritten** [tloncorp/landscape-apps#1571]
This is a difficult-to-characterise bug because it relies upon observations from others, however it was noted by myself and others that notebooks in groups I host vanished for users other than myself after migration to Landscape 1. This is to say that they were visible to me but not to others, despite reporting permissions that should have actually made them world-writable (this may be a separate reportable bug or simply a misreporting of the actual permission state).

I found that this problem was reliably solved on a notebook-by-notebook basis by entering the permissions interface, setting it to the desired permission (members can view, which I construe means that only designated writers can create posts, but other users can comment?) and hitting save. It is unclear if changing the permission or hitting save is the action that fixes this problem.

Thanks to ~monted-tallex, ~silmud-rampel and anyone else who may have assisted in characterising this bug.

**To Reproduce**
Steps to reproduce the behaviour:
1. Migrate a group containing a publicly readable notebook to Landscape 1.
2. Observe that the notebook does not appear for other users.

**Expected behaviour**
Notebooks should retain visibility across migration.

**Additional context:**
- Ship type: planet
- Instance type: self-hosted CLI
- OS/browser: Vivaldi on Linux

**Comment by nohokum** [comment]
Had similar problem in my public group ~bidbel/a. Following the steps suggested above seems to have worked for me in order to achieve desired behavior from notebooks.

A possibly relevant note: Pre-release, my notebooks were set so that only an admin could write to them and anyone could read them. Post-release they were automatically set so that anyone could write to them and anyone could read to them. In practice, this was not the case, because the notebooks were inaccessible to everyone, including me.

But I wonder if some people might unknowingly have usable notebooks with undesired permissions.

**Comment by arthyn** [comment]
reposting these instructions I gave others:

> so I have a version of %groups on ~dilsyr-sibben-nocsyx-lassul that you can install on the host. you can either run `:groups %reset-all-perms` to reset any and all channel permissions for each group the host hosts or you can run `:groups &reset-group-perms [~bidbel %a]` to just try it on that group.

> I would suggest running `|install ~sogryp-dister-dozzod-dozzod %groups` after you run this to make sure you sync to the actual source so you get updates.

> you'll also have to then set the permissions in the interface to what you want

**Comment by arthyn** [comment]
The fix for this was just deployed so you can now run these commands on livenet if your ship is up to date. It should reset all the channel permissions back to open. Let us know how it goes.
