### ISSUE TITLE
notebooks: long urls cause the entire post/viewport to scroll horizontally

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1837]
This issue is what it says on the tin, affect all browsers I've viewed this post in:

https://user-images.githubusercontent.com/1195363/215837664-64646f48-12a2-428e-8b9e-83822d90233e.mov

We might want to consider wrapping long URLs/strings, or truncating them in the least ideal case.

**Comment by romimalta** [comment]
Regardless of the fact that it should not reflect a link but a gif, at the moment the long urls are still breaking the responsive on my devices. It would be optimal a priori to limit the length until this issue is fully addressed.

Also, It should be noted that with the imminent onboarding of several users, being able to throw a gif in the body of an entry should be a priority to avoid vulnerabilities. It would not be convenient (to the platform's reputation) having to explain to new users that they can't put gifs in their publications.
