### ISSUE TITLE
Need to support measurement of failure rate and mean time to failure

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#1901]
I would like to track DORA metrics using sleuth.io, which needs an impact source for failure rate and mean time to recover. More information is available here https://help.sleuth.io/accelerate-metrics/change-failure-rate and here https://help.sleuth.io/accelerate-metrics/mttr. 

Typically this is an endpoint that is retrieved by PagerDuty, DataDog, StatusPage and the like. 

We'll need it for Talk, Groups and Landscape.

**Comment by urcades** [comment]
Is this accounted for with the latest work we've done w/ posthog + hostingmetrics?

**Comment by jamesacklin** [comment]
No. We have no way to measure "failure" because we have no end-to-end tests for a running Landscape. In other words, we're flying blind if something we do in Groups or Talk breaks until we either (A) notice it while running the integration build, or (B) someone submits an issue (see #2331 for a perfect example).
