### ISSUE TITLE
groups: search for group host timeout

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1905]
- Go to Find Groups on a fresh ship
- Search `~nibset-napwyn` (if not on a fresh ship, any host you don't already know)
- Observe it spin and fail (with better failure text now thanks)
- Re-search it a second time after the timeout and observe the group it hosts appear

@jamesacklin and @arthyn this one is pretty bad for onboarding, this action is among the first things a new user does and it looks like they can't join any groups. Is it possible to bump this up the stack?

Tagging @emceetee for context (since she's the one that's been hitting it in onboarding)

**Comment by arthyn** [comment]
I'm not sure what we're missing here. @Fang- @midsum-salrux @philipcmonk if y'all have any insight, here's what I know:

We first check if this ship is known aka in our ames peers: 
https://github.com/tloncorp/landscape-apps/blob/9b7f24ea22af567d6b3c945cecc79ae35776da74/desk/app/groups.hoon#L85

Then if they aren't, we hi them and then send the subscription: 
https://github.com/tloncorp/landscape-apps/blob/9b7f24ea22af567d6b3c945cecc79ae35776da74/desk/app/groups.hoon#L1553

Otherwise we just send the subscription like normal. Perhaps there's something wrong with the order of the hi and sub above or it's malformed?

**Comment by arthyn** [comment]
fwiw I just tried this on two fakezods and it worked perfectly

**Comment by zalberico** [comment]
Are fakezods on the live network?

**Comment by zalberico** [comment]
Checking this out with @Fang- and @arthyn, and it's a timeout issue on the frontend. The search/route works urbit side but the front-end times out before it completes. Once the route is established then things are fast enough on the second search to return before the frontend times out.

Options:
- We have a longer timeout, some sort of back off to a 2min max?
- Use http API to interact with urbit agents on remote ships (this may also have performance gains)
- We could show multiple searches as they're waiting in the UI.

**Comment by jamesacklin** [comment]
We did talk about simply extending the timeout, might be effective enough in the short-term that we can work on the more complex solutions under less pressure.

**Comment by zalberico** [comment]
That makes sense to me
