### ISSUE TITLE
Gallery: long comment breaks the comment box

### ISSUE THREAD

**Issue by galenwp** [tloncorp/landscape-apps#1956]
**Describe the bug, optionally with screenshots**
When you paste in a long comment into a comment box on a gallery post, things look weird.

**To Reproduce**
1. Go to a post in a gallery
2. Paste in a long quote

**Additional context:**
<img width="310" alt="Screen Shot 2023-02-15 at 2 44 29 PM" src="https://user-images.githubusercontent.com/1467211/219205592-af069f91-2853-44c6-b73f-abe91349cdf5.png">

**Comment by urcades** [comment]
This issue has appeared to be fixed somewhere along the way:

https://user-images.githubusercontent.com/1195363/235064510-f95cc7c6-60c5-47ed-aa5c-28b650e4d13e.mov

Unfortunately, a new bug appears to have been introduced whereby the entire preview page will scroll in an unsightly way, with the comment box taking up a lot of the screen and pushing all else aside.

I'm not sure if we should close this issue @jamesacklin , but we should probably fix the newly introduced buggy behavior by ensuring the text overflows within* the comment textarea once it's reached 5-8 lines of text, so that screeds don't break the rest of the interface.
