### ISSUE TITLE
talk: clubs appearing as invitations

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#2408]
**Describe the bug, optionally with screenshots**
Existing club-DMs are appearing as invitations in the sidebar and in the main message pane (accept/deny).

From the wild: 
![image](https://user-images.githubusercontent.com/748181/234644236-79f300d6-83be-4161-9766-87b5fcf0beaa.png)
![image](https://user-images.githubusercontent.com/748181/234644272-ebca2ef3-27fc-4933-ab00-1e509429449f.png)

Small Talk apparently allows you to speak past this gate:
![image](https://user-images.githubusercontent.com/748181/234644765-4f55423a-9409-460f-8b0f-740efada7aa3.png)

**To Reproduce**
No known steps or conditions.

**Comment by thelifeandtimes** [comment]
I have had issues like this where I was invited to a group DM, accepted the invite, and then was able to communicate in the DM. Except, every time I would reopen Talk, the %club would appear as an invitation and I would need to reaccept it to continue the discussion. A few oddities:
1. It appeared to me as though ~sarlev-sarsen was in the member list twice; once as a full member and once as a pending member.
2. I was unable to decline the invitation from the full view. But when selecting the sidebar element for that chat row, I was able to decline the invitation from there and now I am no longer in the chat at all.
3. Since leaving the chat I somehow got an invitation from myself to join a chat with myself:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/82244264/234661322-37f7e9fb-812f-4fbe-9330-1becec49e422.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/82244264/234661370-7bacc4dc-0345-46ba-957e-0e1f841b7e03.png">
Wondering if these are related.
