### ISSUE TITLE
Unable to join any groups after accidentally breaking my planet.

### ISSUE THREAD

**Issue by skilo83** [tloncorp/landscape-apps#2474]
I booted up my first planet and it took some time to boot but i was able to join the tlon group and send messages. later i decided to move my planet to another machine but didn't know i needed to move it's pier with it. so it booted but had weird stuff going on and couldn't access any groups. i wen through the process of a factory reset. deleted all files and folders and started again new, even waited hours to make sure the network stuff took effect. but still had same issue.

Today i booted up a fresh planet and tried to connect to some groups. not even the fresh planet will connect to anything. Not sure what big thing i did wrong but it almost seems like my IP has been blacklisted or something.

Not sure what is showing in the terminal window. Maybe some errors?

`ut=[acked=%.n path=/gangs/index/~rondev]
subscribe wire not unique
%groups
/gangs/index/~rondev
[p=~rondev q=%groups]
error in %groups
%watch-not-unique
! subscribe wire not unique`

also a few of these:

`/sys/vane/gall/hoon:<[1.151 26].[1.151 60]>
peek bad result`

**Comment by jamesacklin** [comment]
Hello, @skilo83. The dojo messages you mention have no bearing on the issue.

It sounds like you double-booted, factory-reset, and then tried to boot again. If you factory-reset over the weekend, the L2 roller was offline (out of ETH) and not processing transactions. As a result you may have inadvertently double-booted again.

I'd recommend another factory reset and boot.

Otherwise, I'd recommend running `+azimuth-block` on your running ship. If it's close to 18,000, you should be OK. If it's not, you can either kick or load to move the state processing along. See this page: https://operators.urbit.org/manual/os/dojo-tools#azimuth-block

It doesn't sound like there are any application errors with Groups or Talk, so I'm closing this issue. 

Your next best bet is to boot a comet, join ~bitbet-bolbel/urbit-community, and ask for help there. You can also email support@urbit.org.

Good luck!
