### ISSUE TITLE
%contact-store not populating

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#2484]
**Describe the bug, optionally with screenshots**
I breached >24 hours ago and I barely have contacts. Everyone appears with a black default sigil and `@p` until I click on their profiles, at which point their info fills in and is visible in all contexts. In Leap I can only get results searching for ships that I've added to `%contact-store` by clicking them.

When I booted, I saw the whole rogues gallery in `~sampel is your neighbour` messages in Terminal, so it's not a peer-discovery issue.

**To Reproduce**
1. Boot a new ship, or breach an L2 ship
2. Join a couple of groups
3. Wait to see if you get contacts
4. Click on profiles to fill in info

**Expected behavior**
Contact details like avatars, display names, and profile info should fill in automatically within <30 minutes of having booted the ship.

**Additional context:**
- L2 planet
- Self-hosting on a daily-driver MacBook Air, having not had time to fix up my real self-hosting setup. It's not like I'm putting the thing to sleep / disconnecting so often it would interrupt the filling in of contact info.

**Comment by jamesacklin** [comment]
This is expected behavior. The new agent, %contacts, subscribes directly to ships for profile updates. 

One can initiate the subscription by clicking on the profile directly or DMing with someone.

We opted for this conservative approach as to not introduce a ton of subscription load and potentially bog down the network with everyone in a large group suddenly (and exponentially) subscribing to one another.

You can track #2467 as we open the aperture more and contact sharing becomes more automatic.
