### ISSUE TITLE
talk: clicking on a `<code>` block should copy to clipboard

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#435]

**Comment by urcades** [comment]
This is something we've wanted to support for a while:

<img width="706" alt="Screenshot 2023-04-28 at 3 46 45 AM" src="https://user-images.githubusercontent.com/1195363/235087005-886419de-420b-4666-b0a7-baccf53d3c47.png">

Should be implemented as a distinct button, rather than applied to the code block as a whole, though.
