### ISSUE TITLE
refs/diary: display reference to notebook channel

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#606]

**Comment by thelifeandtimes** [comment]
Going to mention here since this seems to be an issue for references to notebook posts. The reference that I experience when looking at a notebook post that is just plain text (because it is pure markdown that isn't being parsed, see #1610), the reference is to the entire notebook post and that makes the 'continue reading' button redundant. 
basically channel has a nearly endless scroll that looks like this for a recent post: 
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/82244264/210299446-d5d7dfc6-674c-4c11-a126-4c7e51a19c76.png">

**Comment by arthyn** [comment]
We'll put this in another issue

**Comment by thelifeandtimes** [comment]
As a note, it does seem like this may be solved in some instances as I have definitely seen notebook posts that don't reference the full content. Perhaps if there is a properly parsed header or other content type that renders, rather than it being exclusively plaintext??

**Comment by arthyn** [comment]
Yeah I think it pulls the first verse of content which can be infinitely long lol. Just needs some truncation
