### ISSUE TITLE
heap: list/grid view a writer-setting

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#926]
This is evident when arranging by list or grid in a channel you don't have permission to edit.

To reproduce:
1. Start a Gallery channel in a group on Ship A, an administrator. Mark it as "Members can view."
2. Visit this Gallery using Ship B, a group member. Interact with the grid|list view setting.
3. Observe poke failure, no UI change.

Expected result:
This should be a _per-user setting_ that persists between refreshes/sessions.

**Comment by patosullivan** [comment]
Can repro, but this appears to be a hoon-side issue. Trying to dig in there and see if I can't figure it out.

**Comment by patosullivan** [comment]
Ok, this is more than just a bug in hoon. I think the way we're thinking about this on the backend doesn't match the frontend expectation. 

I think this is intended to be a way for each user to choose how they want to view a particular gallery channel. The way it's implemented now the view is set *per-gallery*, not per-user + per-gallery, so each user will always see whatever the setting is for *that* gallery (not whatever they prefer). So if the gallery permissions are "Open to All" then each user has the ability to change the default view for that channel for all other users.

I think we probably need to store this in settings-store rather than with the heap itself.
